name: Deploy Page (Alternative)

# Manual trigger only
on:
  workflow_dispatch:

# Sets permissions for the GITHUB_TOKEN
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          # Exclude git-related files and workflow files
          exclude_assets: '.github,README.md'